### ISSUE TITLE
ts client issues

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/kittycad.ts#35]
Some issues with the ts client, I think mostly related to ES modules and how the lib is bundled. Though not 100% sure on details at this point.

Something else to note is that while this repo has tests, what it's missing is tests for installing and running after an install from npm, adding samples to the litter box repo is on the TODO list anyway, so I might as samples as way of getting this verification.

This is a pretty good round up of the issues with bundling for npm with the current ecosystem 
https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

**Comment by ghost** [comment]
`Irev-Dev` added this issue to [`2022 Q4 - Ends at Winter Break`](https://github.com/orgs/KittyCAD/projects/13).
 And I (the bot) will remove the issue from KittyCode, (issues shouldn't be in the backlog if they're in another project)
